[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "better-profanity>=0.7.0",
    "nest-asyncio>=1.6.0",
    "python-telegram-bot==20.7",
    "requests>=2.31.0",
    "google-genai>=1.0.0",
    "python-dotenv>=1.0.0",
]
